# Site settings
title: "   大鲨鱼的海底世界"
header-img: "img/Xacebook.jpg"
tagline: ""  
description: ""  
baseurl: ""
url: "http://www.sinkshark.com"  

# About/contact
owner: 
  name: "黄欢"
  email: 2681873307@qq.com
  bio: "大鲨鱼的海底世界"

# Data
gavatar: img/favicon.ico
favicon: img/favicon.ico

#douban_username:  cnfeat
#twitter_username: feat
#github_username: cnfeat
#facebook_username: 
#weibo_username: cnfeat 
#zhihu_username: feat

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "黄欢"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
#comments :
#  provider : disqus
 # duoshuo :
 #   short_name : cnfeat
 # disqus :
  #    short_name : cnfeat

# Analytics and webmaster tools stuff goes here
#google_analytics: UA-80884545-1
#google_verify:
## https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in footer navigation
